apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iam

resources:
  - pgsql-ns.yml
  - pgsql-spc.yaml
  - pgsql-config.yml
  - pgsql-pvc.yml
  - pgsql-secret.yml
  - pgsql.yml

patches:
  - path: patches/node-selector.yaml
    target:
      kind: Deployment
  - path: patches/node-selector.yaml
    target:
      kind: StatefulSet
  - path: patches/node-selector.yaml
    target:
      kind: Job
  - path: patches/node-selector.yaml
    target:
      kind: Cronjob

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: postgres
    newName: gru.ocir.io/grodcxdpuvvy/vivo-altaia/postgres
    newTag: "11.17"