---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: iam-service
  name: iam-service
spec:
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http-proxy
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app.kubernetes.io/instance: iam
    app.kubernetes.io/name: iam-service
  type: NodePort
