
CREATE TABLESPACE TS_IAM_DATA DATAFILE SIZE 32M AUTOEXTEND ON NEXT 64M MAXSIZE 10G LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_IAM_INDX DATAFILE SIZE 32M AUTOEXTEND ON NEXT 64M MAXSIZE 10G LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
